// Example prompts for when there's no image (text-only palette generation)
export const NO_IMAGE_EXAMPLES = [
  'Create a warm autumn palette with golden and crimson tones',
  'Generate ocean blues with seafoam and coral accents',
  'Design a vintage 1970s color scheme',
  'Make a minimalist palette with soft pastels',
  'Create a bold neon cyberpunk color combination',
  'Generate earthy forest colors for a nature brand',
  'Design a luxury gold and black palette',
  'Create sunset colors with pink and orange gradients',
  'Make a calming spa palette with greens and whites',
  'Generate 5 colors inspired by cherry blossoms',
  'Create a desert landscape color scheme',
  'Design a modern tech brand palette',
  'Make a cozy winter cabin color combination',
  'Generate vibrant tropical fruit colors',
  'Create a sophisticated wine bar palette',
  "Design colors for a children's playroom",
  'Make a vintage denim and leather palette',
  'Generate arctic tundra inspired colors',
  'Create a bohemian festival color scheme',
  'Design a corporate professional palette',
  'Make a retro 80s neon color combination',
  'Generate soft morning mist colors',
  'Create a spicy Mexican cuisine palette',
  'Design colors inspired by gemstones',
  'Make a peaceful zen garden color scheme',
  'Generate colors from a lavender field',
  'Create a dramatic gothic color palette',
  'Design bright carnival celebration colors',
  'Make a subtle French countryside palette',
  'Generate colors inspired by Japanese art',
  'Create a fresh spring garden color scheme',
  'Design a warm coffee shop palette',
  'Make colors inspired by Northern Lights',
  'Generate a beachy coastal color combination',
  'Create a sophisticated art gallery palette',
  'Design colors for a wellness brand',
  'Make a bold street art color scheme',
  'Generate soft romantic wedding colors',
  'Create a modern apartment color palette',
  'Design colors inspired by precious metals',
]

// Example prompts for when there's an image (specifications for analysis)
export const WITH_IMAGE_EXAMPLES = [
  "Don't include background colors",
  'Focus on warm tones only',
  'Ignore the text and focus on objects',
  'Extract only the most vibrant colors',
  'Prioritize colors from the center of the image',
  'Skip any white or black areas',
  'Focus on the main subject, ignore the background',
  'Extract muted and subtle tones',
  'Only include colors that appear prominently',
  'Avoid any gray or neutral colors',
  'Focus on the lighting and shadow colors',
  'Extract colors from clothing or fabric only',
  'Prioritize natural colors over artificial ones',
  'Focus on the sky colors in the image',
  'Extract colors from plants or nature elements',
  'Ignore any metallic or reflective surfaces',
  'Focus on skin tones and human elements',
  'Extract colors from the foreground only',
  'Prioritize colors that complement each other',
  'Focus on the emotional mood of the colors',
  'Extract colors from architectural elements',
  'Ignore any branding or logo colors',
  'Focus on the most saturated colors',
  'Extract colors from water or liquid elements',
  'Prioritize colors from the left side of the image',
  'Focus on colors that create contrast',
  'Extract colors from food or organic elements',
  'Ignore any monochrome or grayscale areas',
  'Focus on colors from the bottom third',
  'Extract colors that would work for a brand palette',
]

// Example prompts for editing existing palettes
export const EDITING_EXAMPLES = [
  'Add a warm red color to the palette',
  'Make the third color darker',
  'Change the primary color to blue',
  'Replace the green with a forest green',
  'Add a complementary color to the orange',
  'Make all colors more vibrant',
  'Soften the bright colors',
  'Add a neutral gray color',
  'Remove the yellow and add purple instead',
  'Make the palette more pastel',
  'Increase the saturation of all colors',
  'Add a color that matches the sky',
  'Replace the pink with a coral shade',
  'Make the palette warmer overall',
  'Add a deep navy blue',
  'Change the brown to a chocolate brown',
  'Add a mint green color',
  'Make the red more burgundy',
  'Add a color for text readability',
  'Replace the lightest color with white',
  'Add a golden yellow accent',
  'Make the purple more royal',
  'Add an earthy tone',
  'Change the primary to a teal color',
  'Add a soft pink for highlights',
  'Make the palette more monochromatic',
  'Add a contrasting accent color',
  'Replace the orange with a peach',
  'Add a charcoal color for depth',
  'Make all colors slightly desaturated',
]
